### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by jacebrowning** [lucid281/pyEfi#2]
If you add a description to the top of the Code tab, it will show up in search results and previews:

<img width="407" alt="screen shot 2017-07-31 at 7 02 49 pm" src="https://user-images.githubusercontent.com/939501/28802115-e0396356-7622-11e7-83c1-94bbaa08ad34.png">

**Comment by lucid281** [comment]
![selection_001](https://user-images.githubusercontent.com/13423008/28854910-9ee4b5dc-7707-11e7-88d8-1a1e78161235.png)
